// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjOniqueWebsite.Models.EFModels
{
    public partial class Citys
    {
        public Citys()
        {
            Areas = new HashSet<Areas>();
            Employees = new HashSet<Employees>();
            Members = new HashSet<Members>();
        }

        public int CityId { get; set; }
        public string CityName { get; set; }

        public virtual ICollection<Areas> Areas { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<Members> Members { get; set; }
    }
}