// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjOniqueWebsite.Models.EFModels
{
    public partial class EmployeeLevel
    {
        public EmployeeLevel()
        {
            Employees = new HashSet<Employees>();
        }

        public int EmployeeLevelId { get; set; }
        public string EmployeeLevelName { get; set; }

        public virtual ICollection<Employees> Employees { get; set; }
    }
}