// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjOniqueWebsite.Models.EFModels
{
    public partial class MemberLevel
    {
        public MemberLevel()
        {
            Members = new HashSet<Members>();
        }

        public int MemberLevelId { get; set; }
        public string MemberLevelName { get; set; }

        public virtual ICollection<Members> Members { get; set; }
    }
}