// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjOniqueWebsite.Models.EFModels
{
    public partial class OrderDetails
    {
        public int OrderDetailId { get; set; }
        public string OrderId { get; set; }
        public int StockId { get; set; }
        public int OrderQuantity { get; set; }
        public decimal Price { get; set; }

        public virtual Orders Order { get; set; }
        public virtual ProductStockDetails Stock { get; set; }
    }
}