// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjOniqueWebsite.Models.EFModels
{
    public partial class ProductPhotos
    {
        public ProductPhotos()
        {
            ProductStockDetails = new HashSet<ProductStockDetails>();
        }

        public int ProductPhotoId { get; set; }
        public string ProductPhotoName { get; set; }
        public string ProductPhotoPath { get; set; }

        public virtual ICollection<ProductStockDetails> ProductStockDetails { get; set; }
    }
}