// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjOniqueWebsite.Models.EFModels
{
    public partial class ProductColors
    {
        public ProductColors()
        {
            ProductStockDetails = new HashSet<ProductStockDetails>();
        }

        public int ColorId { get; set; }
        public string ColorName { get; set; }

        public virtual ICollection<ProductStockDetails> ProductStockDetails { get; set; }
    }
}