// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace prjOniqueWebsite.Models.EFModels
{
    public partial class Products
    {
        public Products()
        {
            ProductStockDetails = new HashSet<ProductStockDetails>();
        }

        public int ProductId { get; set; }
        [Display(Name = "商品名稱")]
        [Required(ErrorMessage = "商品名稱不可空白")]
        public string ProductName { get; set; }
        public int ProductCategoryId { get; set; }
        [Display(Name = "商品價格")]
        [Required(ErrorMessage = "商品價格不可空白")]
        public decimal Price { get; set; }
        public string Description { get; set; }
        [Display(Name ="上架時間")]
        [Required(ErrorMessage = "上架時間不可空白")]
        public DateTime AddedTime { get; set; }
        [Display(Name = "下架時間")]
        [Required(ErrorMessage = "下架時間不可空白")]
        public DateTime ShelfTime { get; set; }
        public int SupplierId { get; set; }
        public int? DiscountId { get; set; }
        public string PhotoPath { get; set; }

        public virtual Discounts Discount { get; set; }
        public virtual Categories ProductCategory { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<ProductStockDetails> ProductStockDetails { get; set; }
    }
}