// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjOniqueWebsite.Models.EFModels
{
    public partial class ShippingMethods
    {
        public ShippingMethods()
        {
            Orders = new HashSet<Orders>();
        }

        public int MethodId { get; set; }
        public string MethodName { get; set; }

        public virtual ICollection<Orders> Orders { get; set; }
    }
}