// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjOniqueWebsite.Models.EFModels
{
    public partial class ShoppingCart
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int StockId { get; set; }
        public int OrderQuantity { get; set; }

        public virtual Members Member { get; set; }
        public virtual ProductStockDetails Stock { get; set; }
    }
}